//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicaretBorsasi_Project.Program.SalonSatis.ParametreKodluBilgiIslemleri {
    
    
    public partial class KurulusTurIslemleri {
        
        /// <summary>
        /// ParametreKodluKurulusTurIslemleriUserControl1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::TicaretBorsasi_Project.User_Control.Ortak.ParametreKodluKurulusTurIslemleriUserControl ParametreKodluKurulusTurIslemleriUserControl1;
    }
}
