//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicaretBorsasi_Project.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AIDAT_TAKIP
    {
        public int AidatTakipKey { get; set; }
        public Nullable<int> TuccarSicilKey { get; set; }
        public Nullable<int> DereceKey { get; set; }
        public Nullable<short> Yil { get; set; }
        public Nullable<decimal> AidatMiktar { get; set; }
        public Nullable<System.DateTime> Taksit1OdemeTarihi { get; set; }
        public Nullable<decimal> Taksit1OdemeMiktar { get; set; }
        public string Taksit1OdemeAciklama { get; set; }
        public Nullable<System.DateTime> Taksit2OdemeTarihi { get; set; }
        public Nullable<decimal> Taksit2OdemeMiktar { get; set; }
        public string Taksit2OdemeAciklama { get; set; }
        public Nullable<System.DateTime> Taksit1CezaTarihi { get; set; }
        public Nullable<decimal> Taksit1CezaMiktar { get; set; }
        public string Taksit1CezaAciklama { get; set; }
        public Nullable<System.DateTime> Taksit2CezaTarihi { get; set; }
        public Nullable<decimal> Taksit2CezaMiktar { get; set; }
        public string Taksit2CezaAciklama { get; set; }
        public Nullable<System.DateTime> TahakkukTarihi { get; set; }
        public string TahakkukMahsupNo { get; set; }
        public Nullable<System.Guid> KayitKisiKey { get; set; }
        public Nullable<System.DateTime> KayitTarih { get; set; }
        public Nullable<System.Guid> GuncelleKisiKey { get; set; }
        public Nullable<System.DateTime> GuncelleTarih { get; set; }
    
        public virtual TT_DERECE TT_DERECE { get; set; }
        public virtual TUCCAR_SICIL TUCCAR_SICIL { get; set; }
    }
}
