//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicaretBorsasi_Project.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BANKA_MEVDUAT
    {
        public int BankaMevduatKey { get; set; }
        public string BankaHesapNo { get; set; }
        public string BankaAdi { get; set; }
        public decimal VadeliYatanMeblag { get; set; }
        public System.DateTime VadeBasi { get; set; }
        public System.DateTime VadeSonu { get; set; }
        public double FaizYuzdesi { get; set; }
        public double StopajYuzdesi { get; set; }
        public Nullable<System.Guid> KayitKisiKey { get; set; }
        public Nullable<System.DateTime> KayitTarih { get; set; }
        public Nullable<System.Guid> GuncelleKisiKey { get; set; }
        public Nullable<System.DateTime> GuncelleTarih { get; set; }
    }
}
