//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicaretBorsasi_Project.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BEYAN
    {
        public int BeyanKey { get; set; }
        public Nullable<System.DateTime> BeyanTarihi { get; set; }
        public Nullable<int> BorsaSubeKey { get; set; }
        public string BeyanNo { get; set; }
        public string BeyanSatirNo { get; set; }
        public byte AlisSatisTipKey { get; set; }
        public Nullable<byte> BeyanTipKey { get; set; }
        public string MustahsilNo { get; set; }
        public string SaticiAd { get; set; }
        public string SaticiAdres { get; set; }
        public Nullable<decimal> BeyanMiktar { get; set; }
        public Nullable<decimal> SimsariyeMiktar { get; set; }
        public Nullable<decimal> TescilMiktar { get; set; }
        public Nullable<decimal> Stopaj { get; set; }
        public Nullable<decimal> FonPayiBagkur { get; set; }
        public Nullable<decimal> MeraFonu { get; set; }
        public Nullable<decimal> BirimFiyat { get; set; }
        public Nullable<byte> BirimTipKey { get; set; }
        public string Mensei { get; set; }
        public Nullable<short> UretimYili { get; set; }
        public string OzelSartTanimlama { get; set; }
        public string TeslimMahalli { get; set; }
        public Nullable<System.DateTime> TeslimTarihi { get; set; }
        public string BeyanFaturaNo { get; set; }
        public Nullable<System.DateTime> BeyanFaturaTarihi { get; set; }
        public Nullable<int> TuccarSicilKey { get; set; }
        public Nullable<int> MaddeKodKey { get; set; }
        public Nullable<byte> BeyanKayitTipKey { get; set; }
        public Nullable<short> CanliHayvanAdet { get; set; }
        public Nullable<int> SatisSekliKey { get; set; }
        public Nullable<int> BeyannameKarsiFirmaTuccarSicilKey { get; set; }
        public string KarsiVergiDairesiAdi { get; set; }
        public string KarsiVergiNo { get; set; }
        public string KarsiUnvan { get; set; }
        public string KarsiAdres { get; set; }
        public Nullable<decimal> BeyanSatisTutari { get; set; }
        public string DovizAdi { get; set; }
        public Nullable<decimal> DovizKuru { get; set; }
        public Nullable<decimal> DovizTutari { get; set; }
        public string FisTarihiFisNoFisSatiri { get; set; }
        public Nullable<bool> StopajVarmi { get; set; }
        public string BulunduguYer { get; set; }
        public Nullable<decimal> BeyanTastik { get; set; }
        public Nullable<System.Guid> KayitKisiKey { get; set; }
        public Nullable<System.DateTime> KayitTarih { get; set; }
        public Nullable<System.Guid> GuncelleKisiKey { get; set; }
        public Nullable<System.DateTime> GuncelleTarih { get; set; }
    
        public virtual TT_ALIS_SATIS_TIP TT_ALIS_SATIS_TIP { get; set; }
        public virtual TT_BEYAN_KAYIT_TIP TT_BEYAN_KAYIT_TIP { get; set; }
        public virtual TT_BEYAN_TIP TT_BEYAN_TIP { get; set; }
        public virtual TT_BIRIM_TIP TT_BIRIM_TIP { get; set; }
        public virtual TT_BORSA_SUBE TT_BORSA_SUBE { get; set; }
        public virtual TT_MADDE_KOD TT_MADDE_KOD { get; set; }
        public virtual TT_SATIS_SEKLI TT_SATIS_SEKLI { get; set; }
        public virtual TUCCAR_SICIL TUCCAR_SICIL { get; set; }
        public virtual TUCCAR_SICIL TUCCAR_SICIL1 { get; set; }
    }
}
