//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicaretBorsasi_Project.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBEntities : DbContext
    {
        public DBEntities()
            : base("name=DBEntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<aspnet_Applications> aspnet_Applications { get; set; }
        public DbSet<aspnet_Membership> aspnet_Membership { get; set; }
        public DbSet<aspnet_Paths> aspnet_Paths { get; set; }
        public DbSet<aspnet_PersonalizationAllUsers> aspnet_PersonalizationAllUsers { get; set; }
        public DbSet<aspnet_PersonalizationPerUser> aspnet_PersonalizationPerUser { get; set; }
        public DbSet<aspnet_Profile> aspnet_Profile { get; set; }
        public DbSet<aspnet_Roles> aspnet_Roles { get; set; }
        public DbSet<aspnet_SchemaVersions> aspnet_SchemaVersions { get; set; }
        public DbSet<aspnet_Users> aspnet_Users { get; set; }
        public DbSet<aspnet_WebEvent_Events> aspnet_WebEvent_Events { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<AIDAT_TAKIP> AIDAT_TAKIP { get; set; }
        public DbSet<BANKA_MEVDUAT> BANKA_MEVDUAT { get; set; }
        public DbSet<BEYAN> BEYANs { get; set; }
        public DbSet<DERECE_DEGISIKLIK> DERECE_DEGISIKLIK { get; set; }
        public DbSet<FIRMA_ADRES> FIRMA_ADRES { get; set; }
        public DbSet<FIRMA_DIGER_FAALIYET_KOD> FIRMA_DIGER_FAALIYET_KOD { get; set; }
        public DbSet<FIRMA_FAALIYET> FIRMA_FAALIYET { get; set; }
        public DbSet<FIRMA_KAYITLI_ODA> FIRMA_KAYITLI_ODA { get; set; }
        public DbSet<FIRMA_SAHIS> FIRMA_SAHIS { get; set; }
        public DbSet<FIRMA_TELEFON_FAX> FIRMA_TELEFON_FAX { get; set; }
        public DbSet<FIRMA_UYARI> FIRMA_UYARI { get; set; }
        public DbSet<FIRMA_YETKILI> FIRMA_YETKILI { get; set; }
        public DbSet<FIRMA_YONETIM> FIRMA_YONETIM { get; set; }
        public DbSet<FIS_NO> FIS_NO { get; set; }
        public DbSet<GELEN_GIDEN_EVRAK> GELEN_GIDEN_EVRAK { get; set; }
        public DbSet<HESAP_PLANI> HESAP_PLANI { get; set; }
        public DbSet<KAYIT_TAKIP> KAYIT_TAKIP { get; set; }
        public DbSet<MESLEK_GRUP_DEGISIKLIK> MESLEK_GRUP_DEGISIKLIK { get; set; }
        public DbSet<REHBER> REHBERs { get; set; }
        public DbSet<SERMAYE_DEGISIKLIK> SERMAYE_DEGISIKLIK { get; set; }
        public DbSet<TASDIK_FASIL_AKTARMA_ACIKLAMA> TASDIK_FASIL_AKTARMA_ACIKLAMA { get; set; }
        public DbSet<TESCIL_ORAN> TESCIL_ORAN { get; set; }
        public DbSet<TT_ALIS_SATIS_TIP> TT_ALIS_SATIS_TIP { get; set; }
        public DbSet<TT_BEYAN_KAYIT_TIP> TT_BEYAN_KAYIT_TIP { get; set; }
        public DbSet<TT_BEYAN_TIP> TT_BEYAN_TIP { get; set; }
        public DbSet<TT_BIRIM_TIP> TT_BIRIM_TIP { get; set; }
        public DbSet<TT_BORSA_SUBE> TT_BORSA_SUBE { get; set; }
        public DbSet<TT_DERECE> TT_DERECE { get; set; }
        public DbSet<TT_DERECE_CEZA_ORAN> TT_DERECE_CEZA_ORAN { get; set; }
        public DbSet<TT_DOSYA_GRUP> TT_DOSYA_GRUP { get; set; }
        public DbSet<TT_EVRAK_TIP> TT_EVRAK_TIP { get; set; }
        public DbSet<TT_FIRMA_ADRES_TIP> TT_FIRMA_ADRES_TIP { get; set; }
        public DbSet<TT_FIRMA_TELEFON_FAX_TIP> TT_FIRMA_TELEFON_FAX_TIP { get; set; }
        public DbSet<TT_FIS_TIP> TT_FIS_TIP { get; set; }
        public DbSet<TT_HESAP_PLANI_DOKUM_TIP> TT_HESAP_PLANI_DOKUM_TIP { get; set; }
        public DbSet<TT_IL_ILCE> TT_IL_ILCE { get; set; }
        public DbSet<TT_KONSOLIDE_TIP> TT_KONSOLIDE_TIP { get; set; }
        public DbSet<TT_KURULUS_TUR> TT_KURULUS_TUR { get; set; }
        public DbSet<TT_MADDE_KOD> TT_MADDE_KOD { get; set; }
        public DbSet<TT_MESLEK_GRUP> TT_MESLEK_GRUP { get; set; }
        public DbSet<TT_MUHASEBE_ADI> TT_MUHASEBE_ADI { get; set; }
        public DbSet<TT_MUHASEBE_DURUM_TIP> TT_MUHASEBE_DURUM_TIP { get; set; }
        public DbSet<TT_MUHASEBE_TIP> TT_MUHASEBE_TIP { get; set; }
        public DbSet<TT_OGRENIM_DURUM_TIP> TT_OGRENIM_DURUM_TIP { get; set; }
        public DbSet<TT_SATIS_SEKLI> TT_SATIS_SEKLI { get; set; }
        public DbSet<TT_SICIL_MEMURLUGU> TT_SICIL_MEMURLUGU { get; set; }
        public DbSet<TT_TAHSILAT_TIP> TT_TAHSILAT_TIP { get; set; }
        public DbSet<TT_TASDIK_FASIL_AKTARMA_TIP> TT_TASDIK_FASIL_AKTARMA_TIP { get; set; }
        public DbSet<TT_VERGI_DAIRE> TT_VERGI_DAIRE { get; set; }
        public DbSet<TT_YAZISMA_ADRES> TT_YAZISMA_ADRES { get; set; }
        public DbSet<TUCCAR_ASKI> TUCCAR_ASKI { get; set; }
        public DbSet<TUCCAR_DEPO> TUCCAR_DEPO { get; set; }
        public DbSet<TUCCAR_KEFALET_TEMINAT> TUCCAR_KEFALET_TEMINAT { get; set; }
        public DbSet<TUCCAR_SICIL> TUCCAR_SICIL { get; set; }
        public DbSet<TUCCAR_TAHSIL> TUCCAR_TAHSIL { get; set; }
        public DbSet<UNVAN_DEGISIKLIK> UNVAN_DEGISIKLIK { get; set; }
        public DbSet<YEVMIYE> YEVMIYEs { get; set; }
        public DbSet<BORSA_BILGI> BORSA_BILGI { get; set; }
        public DbSet<DUYURU> DUYURUs { get; set; }
        public DbSet<LOG> LOGs { get; set; }
        public DbSet<SALON_SATIS_AYAR> SALON_SATIS_AYAR { get; set; }
        public DbSet<TT_UYE_TEMINAT_TIP> TT_UYE_TEMINAT_TIP { get; set; }
        public DbSet<SATI> SATIS { get; set; }
        public DbSet<TEKLIF> TEKLIFs { get; set; }
        public DbSet<TESCIL> TESCILs { get; set; }
        public DbSet<TESCIL_KIMLIK> TESCIL_KIMLIK { get; set; }
        public DbSet<TT_MADDE_KOD1> TT_MADDE_KOD1 { get; set; }
        public DbSet<TT_SATICI_URETIM_MERKEZ> TT_SATICI_URETIM_MERKEZ { get; set; }
        public DbSet<TT_TESCIL_PARAMETRE> TT_TESCIL_PARAMETRE { get; set; }
        public DbSet<TT_TOBB_KOD> TT_TOBB_KOD { get; set; }
        public DbSet<URUN> URUNs { get; set; }
    }
}
