//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicaretBorsasi_Project.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class FIRMA_UYARI
    {
        public int FirmaUyariKey { get; set; }
        public int TuccarSicilKey { get; set; }
        public string FirmaUyari { get; set; }
        public Nullable<System.DateTime> FirmaUyariTarih { get; set; }
        public bool Aktif { get; set; }
        public Nullable<System.Guid> KayitKisiKey { get; set; }
        public Nullable<System.DateTime> KayitTarih { get; set; }
        public Nullable<System.Guid> GuncelleKisiKey { get; set; }
        public Nullable<System.DateTime> GuncelleTarih { get; set; }
    
        public virtual TUCCAR_SICIL TUCCAR_SICIL { get; set; }
    }
}
