//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicaretBorsasi_Project.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class GELEN_GIDEN_EVRAK
    {
        public int GelenGidenEvrakKey { get; set; }
        public int DosyaGrupKey { get; set; }
        public Nullable<System.DateTime> KayitTarihi { get; set; }
        public Nullable<int> EvrakSiraNo { get; set; }
        public string AdSoyad { get; set; }
        public string Adres { get; set; }
        public Nullable<int> IlIlceKey { get; set; }
        public Nullable<System.DateTime> EvrakTarihi { get; set; }
        public string EvrakNo { get; set; }
        public string YaziOzeti { get; set; }
        public byte EvrakTipKey { get; set; }
        public Nullable<System.Guid> KayitKisiKey { get; set; }
        public Nullable<System.DateTime> KayitTarih { get; set; }
        public Nullable<System.Guid> GuncelleKisiKey { get; set; }
        public Nullable<System.DateTime> GuncelleTarih { get; set; }
    
        public virtual TT_DOSYA_GRUP TT_DOSYA_GRUP { get; set; }
        public virtual TT_EVRAK_TIP TT_EVRAK_TIP { get; set; }
        public virtual TT_IL_ILCE TT_IL_ILCE { get; set; }
    }
}
