//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicaretBorsasi_Project.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class KAYIT_TAKIP
    {
        public int KayitTakipKey { get; set; }
        public Nullable<int> TuccarSicilKey { get; set; }
        public Nullable<int> DereceKey { get; set; }
        public Nullable<decimal> AidatMiktar { get; set; }
        public Nullable<System.DateTime> OdemeTarihi { get; set; }
        public Nullable<decimal> OdemeMiktar { get; set; }
        public string Aciklama { get; set; }
        public Nullable<System.DateTime> VadeTarihi { get; set; }
        public Nullable<System.DateTime> CezaTarihi { get; set; }
        public Nullable<decimal> CezaMiktar { get; set; }
        public Nullable<System.Guid> KayitKisiKey { get; set; }
        public Nullable<System.DateTime> KayitTarih { get; set; }
        public Nullable<System.Guid> GuncelleKisiKey { get; set; }
        public Nullable<System.DateTime> GuncelleTarih { get; set; }
    
        public virtual TT_DERECE TT_DERECE { get; set; }
        public virtual TUCCAR_SICIL TUCCAR_SICIL { get; set; }
    }
}
