//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicaretBorsasi_Project.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MESLEK_GRUP_DEGISIKLIK
    {
        public int MeslekGrupDegisiklikKey { get; set; }
        public int TuccarSicilKey { get; set; }
        public int MeslekGrupKey { get; set; }
        public Nullable<short> Yil { get; set; }
        public Nullable<System.DateTime> YKKTarih { get; set; }
        public string YKKNo { get; set; }
        public Nullable<System.Guid> KayitKisiKey { get; set; }
        public Nullable<System.DateTime> KayitTarih { get; set; }
        public Nullable<System.Guid> GuncelleKisiKey { get; set; }
        public Nullable<System.DateTime> GuncelleTarih { get; set; }
    
        public virtual TT_MESLEK_GRUP TT_MESLEK_GRUP { get; set; }
        public virtual TUCCAR_SICIL TUCCAR_SICIL { get; set; }
    }
}
