//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicaretBorsasi_Project.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SATI
    {
        public SATI()
        {
            this.TEKLIFs = new HashSet<TEKLIF>();
        }
    
        public int SatisKey { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public int UrunKey { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public Nullable<System.TimeSpan> BaslangicZaman { get; set; }
        public Nullable<System.TimeSpan> BitisZaman { get; set; }
        public decimal BaslangicFiyati { get; set; }
        public Nullable<decimal> BitisFiyati { get; set; }
        public bool AktifMi { get; set; }
        public Nullable<System.Guid> KayitKisiKey { get; set; }
        public Nullable<System.DateTime> KayitTarih { get; set; }
        public Nullable<System.Guid> GuncelleKisiKey { get; set; }
        public Nullable<System.DateTime> GuncelleTarih { get; set; }
    
        public virtual URUN URUN { get; set; }
        public virtual ICollection<TEKLIF> TEKLIFs { get; set; }
    }
}
