//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicaretBorsasi_Project.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TASDIK_FASIL_AKTARMA_ACIKLAMA
    {
        public int TasdikFasilAktarmaAciklamaKey { get; set; }
        public byte TasdikFasilAktarmaTipKey { get; set; }
        public string Aciklama { get; set; }
        public Nullable<System.Guid> KayitKisiKey { get; set; }
        public Nullable<System.DateTime> KayitTarih { get; set; }
        public Nullable<System.Guid> GuncelleKisiKey { get; set; }
        public Nullable<System.DateTime> GuncelleTarih { get; set; }
    
        public virtual TT_TASDIK_FASIL_AKTARMA_TIP TT_TASDIK_FASIL_AKTARMA_TIP { get; set; }
    }
}
