//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicaretBorsasi_Project.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TT_DERECE_CEZA_ORAN
    {
        public int DereceCezaOranKey { get; set; }
        public Nullable<short> Yil { get; set; }
        public Nullable<decimal> Ay1 { get; set; }
        public Nullable<decimal> Ay2 { get; set; }
        public Nullable<decimal> Ay3 { get; set; }
        public Nullable<decimal> Ay4 { get; set; }
        public Nullable<decimal> Ay5 { get; set; }
        public Nullable<decimal> Ay6 { get; set; }
        public Nullable<decimal> Ay7 { get; set; }
        public Nullable<decimal> Ay8 { get; set; }
        public Nullable<decimal> Ay9 { get; set; }
        public Nullable<decimal> Ay10 { get; set; }
        public Nullable<decimal> Ay11 { get; set; }
        public Nullable<decimal> Ay12 { get; set; }
        public Nullable<byte> Taksit1 { get; set; }
        public Nullable<byte> Taksit2 { get; set; }
        public Nullable<System.Guid> KayitKisiKey { get; set; }
        public Nullable<System.DateTime> KayitTarih { get; set; }
        public Nullable<System.Guid> GuncelleKisiKey { get; set; }
        public Nullable<System.DateTime> GuncelleTarih { get; set; }
    }
}
