//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicaretBorsasi_Project.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TT_FIS_TIP
    {
        public TT_FIS_TIP()
        {
            this.FIS_NO = new HashSet<FIS_NO>();
            this.YEVMIYEs = new HashSet<YEVMIYE>();
        }
    
        public byte FisTipKey { get; set; }
        public string FisTipAdi { get; set; }
        public Nullable<System.Guid> KayitKisiKey { get; set; }
        public Nullable<System.DateTime> KayitTarih { get; set; }
        public Nullable<System.Guid> GuncelleKisiKey { get; set; }
        public Nullable<System.DateTime> GuncelleTarih { get; set; }
    
        public virtual ICollection<FIS_NO> FIS_NO { get; set; }
        public virtual ICollection<YEVMIYE> YEVMIYEs { get; set; }
    }
}
