//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicaretBorsasi_Project.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TT_FIRMA_TELEFON_FAX_TIP
    {
        public TT_FIRMA_TELEFON_FAX_TIP()
        {
            this.FIRMA_TELEFON_FAX = new HashSet<FIRMA_TELEFON_FAX>();
        }
    
        public byte FirmaTelefonFaxTipKey { get; set; }
        public string FirmaTelefonFaxTipAdi { get; set; }
        public Nullable<System.Guid> KayitKisiKey { get; set; }
        public Nullable<System.DateTime> KayitTarih { get; set; }
        public Nullable<System.Guid> GuncelleKisiKey { get; set; }
        public Nullable<System.DateTime> GuncelleTarih { get; set; }
    
        public virtual ICollection<FIRMA_TELEFON_FAX> FIRMA_TELEFON_FAX { get; set; }
    }
}
