//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicaretBorsasi_Project.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TT_IL_ILCE
    {
        public TT_IL_ILCE()
        {
            this.GELEN_GIDEN_EVRAK = new HashSet<GELEN_GIDEN_EVRAK>();
            this.TUCCAR_SICIL = new HashSet<TUCCAR_SICIL>();
        }
    
        public int IlIlceKey { get; set; }
        public string Kod { get; set; }
        public string IlIlceAdi { get; set; }
        public string TobbKodu { get; set; }
        public Nullable<System.Guid> KayitKisiKey { get; set; }
        public Nullable<System.DateTime> KayitTarih { get; set; }
        public Nullable<System.Guid> GuncelleKisiKey { get; set; }
        public Nullable<System.DateTime> GuncelleTarih { get; set; }
    
        public virtual ICollection<GELEN_GIDEN_EVRAK> GELEN_GIDEN_EVRAK { get; set; }
        public virtual ICollection<TUCCAR_SICIL> TUCCAR_SICIL { get; set; }
    }
}
