//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicaretBorsasi_Project.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TT_MUHASEBE_DURUM_TIP
    {
        public byte MuhasebeDurumTipKey { get; set; }
        public string MuhasebeDurumTipAdi { get; set; }
    }
}
