//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicaretBorsasi_Project.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TT_SATIS_SEKLI
    {
        public TT_SATIS_SEKLI()
        {
            this.BEYANs = new HashSet<BEYAN>();
        }
    
        public int SatisSekliKey { get; set; }
        public string Kod { get; set; }
        public string SatisSekliAdi { get; set; }
        public string SatisSekliUzunAdi { get; set; }
        public byte SatanKey { get; set; }
        public byte AlanKey { get; set; }
        public byte StopajKey { get; set; }
        public byte TescilKey { get; set; }
        public byte SimsarKey { get; set; }
        public byte TipKey { get; set; }
        public Nullable<System.Guid> KayitKisiKey { get; set; }
        public Nullable<System.DateTime> KayitTarih { get; set; }
        public Nullable<System.Guid> GuncelleKisiKey { get; set; }
        public Nullable<System.DateTime> GuncelleTarih { get; set; }
    
        public virtual ICollection<BEYAN> BEYANs { get; set; }
        public virtual TT_ALIS_SATIS_TIP TT_ALIS_SATIS_TIP { get; set; }
        public virtual TT_ALIS_SATIS_TIP TT_ALIS_SATIS_TIP1 { get; set; }
        public virtual TT_ALIS_SATIS_TIP TT_ALIS_SATIS_TIP2 { get; set; }
        public virtual TT_ALIS_SATIS_TIP TT_ALIS_SATIS_TIP3 { get; set; }
        public virtual TT_ALIS_SATIS_TIP TT_ALIS_SATIS_TIP4 { get; set; }
        public virtual TT_ALIS_SATIS_TIP TT_ALIS_SATIS_TIP5 { get; set; }
    }
}
