//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicaretBorsasi_Project.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TT_TESCIL_PARAMETRE
    {
        public TT_TESCIL_PARAMETRE()
        {
            this.TESCILs = new HashSet<TESCIL>();
        }
    
        public int TescilParametreKey { get; set; }
        public string Kod { get; set; }
        public string Adi { get; set; }
        public bool AlinabilirMi { get; set; }
        public Nullable<System.Guid> KayitKisiKey { get; set; }
        public Nullable<System.DateTime> KayitTarih { get; set; }
        public Nullable<System.Guid> GuncelleKisiKey { get; set; }
        public Nullable<System.DateTime> GuncelleTarih { get; set; }
    
        public virtual ICollection<TESCIL> TESCILs { get; set; }
    }
}
