//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicaretBorsasi_Project.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TT_TASDIK_FASIL_AKTARMA_TIP
    {
        public TT_TASDIK_FASIL_AKTARMA_TIP()
        {
            this.TASDIK_FASIL_AKTARMA_ACIKLAMA = new HashSet<TASDIK_FASIL_AKTARMA_ACIKLAMA>();
        }
    
        public byte TasdikFasilAktarmaTipKey { get; set; }
        public string TasdikFasilAktarmaTipAdi { get; set; }
    
        public virtual ICollection<TASDIK_FASIL_AKTARMA_ACIKLAMA> TASDIK_FASIL_AKTARMA_ACIKLAMA { get; set; }
    }
}
