//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicaretBorsasi_Project.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TT_VERGI_DAIRE
    {
        public TT_VERGI_DAIRE()
        {
            this.TUCCAR_SICIL = new HashSet<TUCCAR_SICIL>();
            this.TUCCAR_TAHSIL = new HashSet<TUCCAR_TAHSIL>();
        }
    
        public int VergiDaireKey { get; set; }
        public string Kod { get; set; }
        public string VergiDairesiAdi { get; set; }
        public string TobbNo { get; set; }
        public Nullable<System.Guid> KayitKisiKey { get; set; }
        public Nullable<System.DateTime> KayitTarih { get; set; }
        public Nullable<System.Guid> GuncelleKisiKey { get; set; }
        public Nullable<System.DateTime> GuncelleTarih { get; set; }
    
        public virtual ICollection<TUCCAR_SICIL> TUCCAR_SICIL { get; set; }
        public virtual ICollection<TUCCAR_TAHSIL> TUCCAR_TAHSIL { get; set; }
    }
}
