//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicaretBorsasi_Project.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TUCCAR_DEPO
    {
        public int TuccarDepoKey { get; set; }
        public Nullable<int> TuccarSicilKey { get; set; }
        public Nullable<int> MaddeKodKey { get; set; }
        public Nullable<decimal> Devir1 { get; set; }
        public Nullable<decimal> Alis1 { get; set; }
        public Nullable<decimal> Satis1 { get; set; }
        public Nullable<decimal> DigerBorsaAlis1 { get; set; }
        public Nullable<decimal> DigerBorsaSatis1 { get; set; }
        public Nullable<decimal> Devir2 { get; set; }
        public Nullable<decimal> Alis2 { get; set; }
        public Nullable<decimal> Satis2 { get; set; }
        public Nullable<decimal> DigerBorsaAlis2 { get; set; }
        public Nullable<decimal> DigerBorsaSatis2 { get; set; }
        public Nullable<System.Guid> KayitKisiKey { get; set; }
        public Nullable<System.DateTime> KayitTarih { get; set; }
        public Nullable<System.Guid> GuncelleKisiKey { get; set; }
        public Nullable<System.DateTime> GuncelleTarih { get; set; }
    
        public virtual TT_MADDE_KOD TT_MADDE_KOD { get; set; }
        public virtual TUCCAR_SICIL TUCCAR_SICIL { get; set; }
    }
}
