//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicaretBorsasi_Project.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TUCCAR_TAHSIL
    {
        public int TuccarTahsilKey { get; set; }
        public Nullable<int> TuccarSicilKey { get; set; }
        public Nullable<System.DateTime> TahsilTarihi { get; set; }
        public string TahsilNo { get; set; }
        public Nullable<decimal> Miktar { get; set; }
        public Nullable<int> VergiDaireKey { get; set; }
        public Nullable<byte> Ay { get; set; }
        public string Aciklama { get; set; }
        public Nullable<System.Guid> KayitKisiKey { get; set; }
        public Nullable<System.DateTime> KayitTarih { get; set; }
        public Nullable<System.Guid> GuncelleKisiKey { get; set; }
        public Nullable<System.DateTime> GuncelleTarih { get; set; }
    
        public virtual TT_VERGI_DAIRE TT_VERGI_DAIRE { get; set; }
        public virtual TUCCAR_SICIL TUCCAR_SICIL { get; set; }
    }
}
