//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicaretBorsasi_Project.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TUCCAR_ASKI
    {
        public int TuccarAskiKey { get; set; }
        public Nullable<int> TuccarSicilKey { get; set; }
        public Nullable<System.DateTime> AskiTarihi { get; set; }
        public string AskiKararNo { get; set; }
        public string AskiAciklama { get; set; }
        public Nullable<System.DateTime> BitisTarihi { get; set; }
        public string BitisKararNo { get; set; }
        public string BitisAciklama { get; set; }
        public Nullable<System.Guid> KayitKisiKey { get; set; }
        public Nullable<System.DateTime> KayitTarih { get; set; }
        public Nullable<System.Guid> GuncelleKisiKey { get; set; }
        public Nullable<System.DateTime> GuncelleTarih { get; set; }
    
        public virtual TUCCAR_SICIL TUCCAR_SICIL { get; set; }
    }
}
