//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicaretBorsasi_Project.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class YEVMIYE
    {
        public int YevmiyeKey { get; set; }
        public int MuhasebeTipKey { get; set; }
        public int HesapPlaniKey { get; set; }
        public byte FisTipKey { get; set; }
        public System.DateTime FisTarih { get; set; }
        public string FisNo { get; set; }
        public string SatirNo { get; set; }
        public string Aciklama { get; set; }
        public decimal Borc { get; set; }
        public decimal Alacak { get; set; }
        public Nullable<System.Guid> KayitKisiKey { get; set; }
        public Nullable<System.DateTime> KayitTarih { get; set; }
        public Nullable<System.Guid> GuncelleKisiKey { get; set; }
        public Nullable<System.DateTime> GuncelleTarih { get; set; }
    
        public virtual HESAP_PLANI HESAP_PLANI { get; set; }
        public virtual TT_FIS_TIP TT_FIS_TIP { get; set; }
        public virtual TT_MUHASEBE_TIP TT_MUHASEBE_TIP { get; set; }
    }
}
